### ISSUE TITLE
 type AffectsChiselPrefix is not a member of package chisel3.experimental

### ISSUE THREAD

**Issue by pxs7** [chipsalliance/chisel3#2638]
[error] ## Exception when compiling 20 sources to out\foreign-modules\rocket-chip\hardfloat\hardfloat\compile.dest\classes
[error] scala.reflect.internal.Types$TypeError: type AffectsChiselPrefix is not a member of package chisel3.experimental

AffectsChiselPrefix  is not  a member of  chisel3.experimental， why use that？

**Comment by jackkoenig** [comment]
AffectsChiselPrefix **is** a member of chisel3.experimental, but currently only in Chisel 3.6-SNAPSHOT an 3.5-SNAPSHOT. It will be released as part of Chisel 3.5.4, so assuming you are using a released version of Chisel, you will need to wait for the next release to use it.

**Comment by pxs7** [comment]
> AffectsChiselPrefix **is** a member of chisel3.experimental, but currently only in Chisel 3.6-SNAPSHOT an 3.5-SNAPSHOT. It will be released as part of Chisel 3.5.4, so assuming you are using a released version of Chisel, you will need to wait for the next release to use it.

thanks

**Comment by pxs7** [comment]
> 

 when  will  Chisel 3.5.4 will be released

**Comment by pxs7** [comment]
> AffectsChiselPrefix **is** a member of chisel3.experimental, but currently only in Chisel 3.6-SNAPSHOT an 3.5-SNAPSHOT. It will be released as part of Chisel 3.5.4, so assuming you are using a released version of Chisel, you will need to wait for the next release to use it.

when will Chisel 3.5.4  be released

**Comment by jackkoenig** [comment]
> when will Chisel 3.5.4 be released

Soon, probably tomorrow.

**Comment by jackkoenig** [comment]
I have released [Chisel v3.5.4](https://github.com/chipsalliance/chisel3/releases/tag/v3.5.4)

**Comment by pxs7** [comment]
> I have released [Chisel v3.5.4](https://github.com/chipsalliance/chisel3/releases/tag/v3.5.4)

Thanks， the error stills exists, the original define for AffectsChiselPrefix as follows

    private val shouldMatchInstance: Type => Boolean = shouldMatchGen(tq"chisel3.experimental.hierarchy.Instance[_]")
    private val shouldMatchChiselPrefixed: Type => Boolean =
      shouldMatchGen(
        tq"chisel3.experimental.AffectsChiselPrefix"
      )

it seams that mill can not recognise the code, and fails found AffectsChiselPrefix,  [mill version =0.10.4],

**Comment by pxs7** [comment]
> I have released [Chisel v3.5.4](https://github.com/chipsalliance/chisel3/releases/tag/v3.5.4)

compile success，  thanks
